### ISSUE TITLE
Setup deploy action

### ISSUE THREAD

**Issue by mvdicarlo** [mvdicarlo/postybirb#202]
Being able to deploy automatically when tag to a commit occurs would be wonderful.

Could explore the electron-builder action.
Would just need to figure out how to manually run the electron-builder successfully locally instead of using the nx-electron's obfuscated one.

```
name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
```
